---
title: "permute_rf_strobl_xor_mtry"
author: "Kelvyn Bladen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
s <- Sys.time()
library(ggplot2)
library(GGally)
library(ggeasy)
library(randomForest)
library(dplyr)
library(randomForestVIP)
library(tidyr)
```

```{r}
rsq = vector(length = 8)

rf_oob_t <- mat.or.vec(8, 8)
rf_oob_f <- mat.or.vec(8, 8)
# rf_pdp <- mat.or.vec(8, 8)

perm_train <- mat.or.vec(8, 8)
drop_train <- mat.or.vec(8, 8)

perm_valid <- mat.or.vec(8, 8)
drop_valid <- mat.or.vec(8, 8)

mrep <- 20
n_size = 1000
set.seed(123)

for (j in seq_len(mrep)) {
    sig <- diag(1, 8, 8)
  
    for (ii in 1:4) {
      for (jj in 1:4) {
        sig[ii, jj] <- ifelse(ii == jj, 1, 0.95)
      }
    }
    
    strobl <- MASS::mvrnorm(n_size, mu = rep(0, 8), Sigma = sig)
    
    y <- 4 * strobl[, 1]*strobl[, 2] + 2 * strobl[, 3]*strobl[, 4] + 
      strobl[, 5]*strobl[, 6] + rnorm(n_size, mean = 0, sd = .1)
    strobl <- data.frame(cbind(strobl, y))
    
    dfv <- MASS::mvrnorm(n_size, mu = rep(0, 8), Sigma = sig)
    y <- 4 * dfv[, 1]*dfv[, 2] + 2 * dfv[, 3]*dfv[, 4] + 
      dfv[, 5]*dfv[, 6] + rnorm(n_size, mean = 0, sd = .1)
    dfv <- data.frame(cbind(dfv, y))
    
  for (k  in seq_len(8)) {
    r <- randomForest(y ~ ., data = strobl, mtry = k,
                      importance = T)
    
    impt <- sqrt(as.data.frame(pmax(randomForest::importance(r, scale = T), 0)))
    impt <- impt$`%IncMSE`[1:8]
    
    impf <- sqrt(as.data.frame(pmax(randomForest::importance(r, scale = F), 0)))
    impf <- impf$`%IncMSE`[1:8]
    
    # vimp = pdp_compare(r, var_vec = 1:8, trellis = F)
    # impp = vimp$imp[c(1, 4)] %>% arrange(var) %>% pull(sd)
    
    # vimp = vip::vi_firm(r, train = strobl)
    # impp <- vimp$Importance[1:8]
    
    p <- predict(r, strobl)
    m = mean((p-strobl$y)^2)
    
    rq = r$rsq[500]
    
    vp <- predict(r, dfv)
    mv = mean((vp-dfv$y)^2)
    
    perm_impr <- vector(length = 8)
    perm_impv <- vector(length = 8)
    drop_impr <- vector(length = 8)
    drop_impv <- vector(length = 8)
    
    for (i in seq_len(8)) {
      df_new <- strobl
      df_new[i] <- df_new[sample(1:n_size), i]
      
      p <- predict(r, df_new)
      new_m = mean((p-strobl$y)^2)
      perm_impr[i] <- new_m - m
      
      ##########################################
      
      v_new <- dfv
      v_new[i] <- v_new[sample(1:n_size), i]
      
      vp <- predict(r, v_new)
      new_vm = mean((vp-dfv$y)^2)
      perm_impv[i] <- new_vm - mv
      
      ###########################################
      
      df_new <- strobl
      df_new[, i] <- 0
      
      p <- predict(r, df_new)
      new_m = mean((p-strobl$y)^2)
      drop_impr[i] <- new_m - m
      
      ##############################################
  
      v_new <- dfv
      v_new[, i] <- 0
  
      vp <- predict(r, v_new)
      new_vm = mean((vp-dfv$y)^2)
      drop_impv[i] <- new_vm - mv
    }
    
    rf_oob_t[,k] <- rf_oob_t[,k] + impt / mrep
    rf_oob_f[,k] <- rf_oob_f[,k] + impf / mrep
    
    # rf_pdp[,k] <- rf_pdp[,k] + impp / mrep
    
    rsq[k] <- rsq[k] + rq / mrep
    
    simpr <- sqrt(pmax(perm_impr, 0))
    perm_train[,k] <- perm_train[,k] + simpr / mrep
    
    simpv <- sqrt(pmax(perm_impv, 0))
    perm_valid[,k] <- perm_valid[,k] + simpv / mrep
    
    dsimpr <- sqrt(pmax(drop_impr, 0))
    drop_train[,k] <- drop_train[,k] + dsimpr / mrep
    
    dsimpv <- sqrt(pmax(drop_impv, 0))
    drop_valid[,k] <- drop_valid[,k] + dsimpv / mrep
  }
  
}
```

\newpage

```{r, message=FALSE, warning=FALSE}
for (i in seq_len(8)){
  sdf <- data.frame(coef = c(4,4,2,2,1,1,0,0),
                    rf_oob_t = rf_oob_t[,i],
                    rf_oob_f = rf_oob_f[,i],
                    # rf_pdp = rf_pdp[,i],
                    perm_train = perm_train[,i], 
                    drop_train = drop_train[,i],
                    perm_valid = perm_valid[,i],
                    drop_valid = drop_valid[,i])

  sdf <- sdf %>% select(coef, rf_oob_f, #rf_pdp, 
                        perm_train, perm_valid)
  print(sdf)
  print(ggpairs(sdf))
}
```

```{r, message=FALSE, warning=FALSE}
rsq

Names = c("V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8")

mag <- dplyr::case_when(Names %in% c("V1", "V2") ~ 4,
                 Names %in% c("V3", "V4") ~ 2,
                 Names %in% c("V5", "V6") ~ 1,
                 .default = 0)

Names <- factor(Names,
                levels = c("V1", "V2", "V3", "V4", 
                           "V5","V6","V7","V8"), ordered = T)
Names <- factor(Names, ordered = F)

rf_oob_f1 = data.frame(rf_oob_f, Names, mag)
# rf_pdp1 = data.frame(rf_pdp, Names, mag)
perm_train1 = data.frame(perm_train, Names, mag)
drop_valid1 = data.frame(drop_valid, Names, mag)
perm_valid1 = data.frame(perm_valid, Names, mag)

colnames(rf_oob_f1)[1:8] <- 1:8
rf_oob_f1 <- rf_oob_f1 %>% pivot_longer(!c(Names,mag), names_to = "mtry",
                                        values_to = "Imp")
rf_oob_f1$mtry <- as.numeric(rf_oob_f1$mtry)

# colnames(rf_pdp1)[1:8] <- 1:8
# rf_pdp1 <- rf_pdp1 %>% pivot_longer(!c(Names,mag), names_to = "mtry",
#                                         values_to = "Imp")
# rf_pdp1$mtry <- as.numeric(rf_pdp1$mtry)

colnames(perm_train1)[1:8] <- 1:8
perm_train1 <- perm_train1 %>% 
  pivot_longer(!c(Names,mag), names_to = "mtry", values_to = "Imp")
perm_train1$mtry <- as.numeric(perm_train1$mtry)

colnames(drop_valid1)[1:8] <- 1:8
drop_valid1 <- drop_valid1 %>% 
  pivot_longer(!c(Names,mag), names_to = "mtry", values_to = "Imp")
drop_valid1$mtry <- as.numeric(drop_valid1$mtry)

colnames(perm_valid1)[1:8] <- 1:8
perm_valid1 <- perm_valid1 %>% 
  pivot_longer(!c(Names,mag), names_to = "mtry", values_to = "Imp")
perm_valid1$mtry <- as.numeric(perm_valid1$mtry)

ma = max(rf_oob_f1$Imp, perm_train1$Imp, perm_valid1$Imp, drop_valid1$Imp)
# mp = max(rf_pdp1$Imp)

gr <- rf_oob_f1 %>%
  ggplot(aes(x = mtry, y = Imp, color = Names, 
             group = Names, linetype = Names, 
             shape = Names)) +
  geom_line() +
  scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
  scale_y_continuous(limits = c(0,max(rf_oob_f1$Imp))) +
  #scale_y_continuous(limits = c(0,4), breaks = seq(0,4,by=1)) +
  ggtitle("OOB PaP Variable Importance") + 
  geom_point(size = 5) +
  scale_linetype_manual(values = rep(2, each = 8)) +
  scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
  scale_size(range = c(6,6)) +
  ylab("Importance") + 
  guides(size = "none") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        plot.title = element_text(size = 14, face = "bold")) +
  easy_center_title() + easy_plot_legend_size(size = 11)
gr
# ggsave("xor_oob_zoom.pdf", plot = last_plot(), dpi = 2400,
#        width = 6, height = 6)

gp <- perm_train1 %>%
  ggplot(aes(x = mtry, y = Imp, color = Names, 
             group = Names, linetype = Names, 
             shape = Names)) +
  geom_line() +
  scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
  scale_y_continuous(limits = c(0,max(perm_train1$Imp))) +
  #scale_y_continuous(limits = c(0,4), breaks = seq(0,4,by=1)) +
  ggtitle("Training PaP Variable Importance") + 
  geom_point(size = 5) +
  scale_linetype_manual(values = rep(2, each = 8)) +
  scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
  scale_size(range = c(6,6)) +
  ylab("Importance") + 
  guides(size = "none") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        plot.title = element_text(size = 14, face = "bold")) +
  easy_center_title() + easy_plot_legend_size(size = 11)
gp
# ggsave("xor_train_zoom.pdf", plot = last_plot(), dpi = 2400,
#        width = 6, height = 6)

gd <- drop_valid1 %>%
  ggplot(aes(x = mtry, y = Imp, color = Names, 
             group = Names, linetype = Names, 
             shape = Names)) +
  geom_line() +
  scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
  scale_y_continuous(limits = c(0,max(drop_valid1$Imp))) +
  #scale_y_continuous(limits = c(0,4), breaks = seq(0,4,by=1)) +
  ggtitle("Validation PaP Variable Importance") + 
  geom_point(size = 5) +
  scale_linetype_manual(values = rep(2, each = 8)) +
  scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
  scale_size(range = c(6,6)) +
  ylab("Importance") + 
  guides(size = "none") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        plot.title = element_text(size = 14, face = "bold")) +
  easy_center_title() + easy_plot_legend_size(size = 11)
gd

gv <- perm_valid1 %>%
  ggplot(aes(x = mtry, y = Imp, color = Names, 
             group = Names, linetype = Names, 
             shape = Names)) +
  geom_line() +
  scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
  scale_y_continuous(limits = c(0,max(perm_valid1$Imp))) +
  #scale_y_continuous(limits = c(0,4), breaks = seq(0,4,by=1)) +
  ggtitle("Validation PaP Variable Importance") + 
  geom_point(size = 5) +
  scale_linetype_manual(values = rep(2, each = 8)) +
  scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
  scale_size(range = c(6,6)) +
  ylab("Importance") + 
  guides(size = "none") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        plot.title = element_text(size = 14, face = "bold")) +
  easy_center_title() + easy_plot_legend_size(size = 11)
gv
# ggsave("xor_val_zoom.pdf", plot = last_plot(), dpi = 2400,
#        width = 6, height = 6)

# gpp <- rf_pdp1 %>%
#   ggplot(aes(x = mtry, y = Imp, color = Names, 
#              group = Names, linetype = Names, 
#              shape = Names)) +
#   geom_line() +
#   scale_linetype_manual(values = rep(2, each = 8)) +
#   scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
#   scale_y_continuous(limits = c(0,max(rf_pdp1$Imp))) +
#   #scale_y_continuous(limits = c(0,4), breaks = seq(0,4,by=1)) +
#   ggtitle("PDP Variable Importance") + 
#   geom_point(size = 5) +
#   scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
#   scale_size(range = c(6,6)) +
#   ylab("Importance") + 
#   guides(size = "none") +
#   theme(axis.text = element_text(size = 12),
#         axis.title = element_text(size = 15),
#         plot.title = element_text(size = 14, face = "bold")) +
#   easy_center_title() + easy_plot_legend_size(size = 11)
# gpp
# ggsave("xor_pdp_zoom.pdf", plot = last_plot(), dpi = 2400,
#        width = 6, height = 6)

library(patchwork)
gr + gp + gd + gv
ggsave("xor_all_zoom.pdf", plot = gr + gp + gd + gv, dpi = 2400,
       width = 9, height = 9)
```

\newpage

```{r}
gr <- rf_oob_f1 %>%
  ggplot(aes(x = mtry, y = Imp, color = Names, 
             group = Names, linetype = Names, 
             shape = Names)) +
  geom_line() +
  scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
  scale_y_continuous(limits = c(0,ma)) +
  ggtitle("OOB PaP Variable Importance") + 
  geom_point(size = 5) +
  scale_linetype_manual(values = rep(2, each = 8)) +
  scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
  scale_size(range = c(6,6)) +
  ylab("Importance") + 
  guides(size = "none") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        plot.title = element_text(size = 14, face = "bold")) +
  easy_center_title() + easy_plot_legend_size(size = 11)
gr
# ggsave("xor_oob.pdf", plot = last_plot(), dpi = 2400,
#        width = 6, height = 6)

gp <- perm_train1 %>%
  ggplot(aes(x = mtry, y = Imp, color = Names, 
             group = Names, linetype = Names, 
             shape = Names)) +
  geom_line() +
  scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
  scale_y_continuous(limits = c(0,ma)) +
  ggtitle("Training PaP Variable Importance") + 
  geom_point(size = 5) +
  scale_linetype_manual(values = rep(2, each = 8)) +
  scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
  scale_size(range = c(6,6)) +
  ylab("Importance") + 
  guides(size = "none") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        plot.title = element_text(size = 14, face = "bold")) +
  easy_center_title() + easy_plot_legend_size(size = 11)
gp
# ggsave("xor_train.pdf", plot = last_plot(), dpi = 2400,
#        width = 6, height = 6)

gd <- drop_valid1 %>%
  ggplot(aes(x = mtry, y = Imp, color = Names, 
             group = Names, linetype = Names, 
             shape = Names)) +
  geom_line() +
  scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
  scale_y_continuous(limits = c(0,ma)) +
  ggtitle("Validation PaP Variable Importance") + 
  geom_point(size = 5) +
  scale_linetype_manual(values = rep(2, each = 8)) +
  scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
  scale_size(range = c(6,6)) +
  ylab("Importance") + 
  guides(size = "none") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        plot.title = element_text(size = 14, face = "bold")) +
  easy_center_title() + easy_plot_legend_size(size = 11)
gd

gv <- perm_valid1 %>%
  ggplot(aes(x = mtry, y = Imp, color = Names, 
             group = Names, linetype = Names, 
             shape = Names)) +
  geom_line() +
  scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
  scale_y_continuous(limits = c(0,ma)) +
  ggtitle("Validation PaP Variable Importance") + 
  geom_point(size = 5) +
  scale_linetype_manual(values = rep(2, each = 8)) +
  scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
  scale_size(range = c(6,6)) +
  ylab("Importance") + 
  guides(size = "none") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 15),
        plot.title = element_text(size = 14, face = "bold")) +
  easy_center_title() + easy_plot_legend_size(size = 11)
gv
# ggsave("xor_val.pdf", plot = last_plot(), dpi = 2400,
#        width = 6, height = 6)

# gpp <- rf_pdp1 %>%
#   ggplot(aes(x = mtry, y = Imp, color = Names, 
#              group = Names, linetype = Names, 
#              shape = Names)) +
#   geom_line() +
#   scale_linetype_manual(values = rep(2, each = 8)) +
#   scale_x_continuous(limits = c(1,8), breaks = seq(2,8,by=2)) +
#   scale_y_continuous(limits = c(0,mp)) +
#   ggtitle("PDP Variable Importance") + 
#   geom_point(size = 5) +
#   scale_shape_manual(values = c(52,52,50,50,49,49,48,48)) +
#   scale_size(range = c(6,6)) +
#   ylab("Importance") + 
#   guides(size = "none") +
#   theme(axis.text = element_text(size = 12),
#         axis.title = element_text(size = 15),
#         plot.title = element_text(size = 14, face = "bold")) +
#   easy_center_title() + easy_plot_legend_size(size = 11)
# gpp
# ggsave("xor_pdp.pdf", plot = last_plot(), dpi = 2400,
#        width = 6, height = 6)

library(patchwork)
gr + gp + gd + gv
ggsave("xor_all.pdf", plot = gr + gp + gd + gv, dpi = 2400,
       width = 9, height = 9)

Sys.time() - s
```

